name: Continuous Integration
on: [push]

env:
  MAJOR_VERSION: 0
  MINOR_VERSION: 1
  PATCH_VERSION: 0

jobs:
  github-bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Bump version
        run: |
          git config --global user.email "joshloecker@icloud.com"
          git config --global user.name "Josh Loecker"
          git fetch --tags
          wget -O - https://raw.githubusercontent.com/treeder/bump/master/gitbump.sh | bash
  

  dockerhub-push:
    runs-on: ubuntu-latest
    name: Checkout Repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags:
